## functions for processing sequence files generated by STRaitrazor 2
library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)

### -----Process Sequences Files -----------------------------------------------
###
### functions for reading sequence files generated by straitrazor  
### and compiling into a single data frame
###
process_sequence_file <- function(seq_file, read){
    df <- try(read.table(seq_file,sep ="\t", stringsAsFactors=F))
    if(class(df)=='try-error') {
        warning(paste0(seq_file, "is empty"))
        return()
    }
    read.table(file=seq_file, header=FALSE, sep="\t") %>% 
        separate(V1, into = c("Locus", "Allele"), sep = ":") %>% 
        rename(Allele_Calls = V4, Size = V2, Sequence = V3) %>% 
        mutate(Allele_Calls = as.integer(Allele_Calls), Read = read)
}


process_sequences_directory <- function(root_dir, paired = TRUE){
    df <- data_frame()
    if(paired){
        for(read in c("R1", "R2")){
            directory <- paste0(root_dir,"/", read,"/")
            for(seq_file in list.files(directory, "sequences",full.names = TRUE)){
                df %<>% bind_rows(process_sequence_file(seq_file,read))
            }
        }
    }else{
        #%%TODO%%
        warning("No code for unpaired read data")
    }
    df
}

### -----Process Allele Calls Files --------------------------------------------
###
### functions for reading allele calls files generated by straitrazor 
### and compiling into a single data frame
###

process_allelecalls_file <- function(txt_file, read){
    # no need to name differently from process_seqeunces as they are in 
    # different environments, they can't see eachother
    df <- try(read.table(txt_file,sep =",", stringsAsFactors=F))
    if(class(df)=='try-error') {
        warning(paste0(txt_file, "is empty"))
        return()
    }
    read.table(txt_file, sep=",", stringsAsFactors=F) %>% 
        head(-1) %>% 
        separate(V1, 
                 into = c("Locus", "Read", "Locus", "Allele", "Allele_Calls"), 
                 sep = ":")  
    
}

process_allelecalls_directory <- function(root_dir, paired = TRUE){
    df <- data_frame()
    if(paired){
        for(read in c("R1", "R2")){
            directory <- paste0(root_dir,"/", read,"/")
            for(txt_file in list.files(directory, "txt",full.names = TRUE)){
                df %<>% bind_rows(process_allelecalls_file(txt_file,read))
            }
            
        }
    }else{
        #%%TODO%%
        warning("No code for unpaired read data")
    }
    df
}

