---
title: "STRait Razor data"
output: html_document
---

pass R1/R2 to processlocus
or loop it and pass the directory
nested for loop
    outer - locus (list of locus names)
    inner - r1 & r2
        setwd to r1 or r2
        call process_locus 
        create r1/locus variable 
        
directory & locus name variable     

left_join or right_join full_join anti_join


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```



```{r}

process_locus <- function (locus, directory=".") { 
    seq_file <- paste0(directory, locus, ".sequences")
    txt_file <- paste0(directory, locus, ".Allelecalls.txt")
    loc_dat <- read.table(file=seq_file, header=FALSE, sep="\t")


    loc_dat2 <- loc_dat %>% separate(V1, into = c("Locus", "Allele"), sep = ":") %>% 
                        rename(Allele_Calls = V4) %>% mutate(Allele_Calls = as.integer(Allele_Calls))
    loc_dat2 <- loc_dat2[,-c(3,4)]
    
    loc2_dat <- read.table(file=txt_file, header=FALSE, sep="\t")
    loc2_dat2 <- head(loc2_dat, -1) 
    loc2_dat2 <- loc2_dat2 %>% separate(V1, into = c("Locus", "Read", "Locus", "Allele", "Allele_Calls"), sep = ":") 
    loc2_dat2$Allele_Calls <- NULL
    
    loc2_dat2 <- loc2_dat2[,-c(2:3)]
    loc2_dat2[loc2_dat2==""]  <- 0 
    loc2_dat2$Allele_Calls<-as.integer(loc2_dat2$Allele_Calls)
    loc2_dat2 <- loc2_dat2[loc2_dat2$Allele_Calls == 0,]
    
    bind_rows(loc_dat2, loc2_dat2)
       
}
    

```
  

```{r, include=FALSE}

strdir <- "/Users/sew/Downloads/H12-H-ZT80925_S96_L001_R1_001.fastq.STRaitRazor copy/PE_MiSeq_ALL"
readdir <- paste0(strdir, "/R1/")
loc_dat3 <- process_locus("D5S818", readdir)

```

```{r, echo=FALSE, include=FALSE}
ggplot(data=loc_dat3, aes(x=Allele, y=AlleleCalls, fill=Allele)) +
    geom_bar(stat="identity") + 
    guides(fill=FALSE) + 
    ylab("Coverage") + 
    ggtitle(loc_dat3$Locus) +
    theme(axis.text.x = element_text(angle = 40, hjust = 1)) 

```

```{r, echo=FALSE}
ggplot(data=loc_dat3, aes(x=Allele, y=AlleleCalls, fill=factor(AlleleCalls), order=AlleleCalls)) +
    geom_bar(stat="identity") + 
    ylab("Coverage") + 
    ggtitle(loc_dat3$Locus) + 
    guides(fill=guide_legend(title="Coverage")) +
    theme(axis.text.x = element_text(angle = 60, hjust = 1)) 
```


